### ISSUE TITLE
[Bug]: Illuminate\Database\MySqlConnection::reconnectIfMissingConnection does not exist

### ISSUE THREAD

**Issue by radiatecode** [tpetry/laravel-mysql-explain#4]
### What happened?

According to your documentation i install your package and add the explain methods (explainForHumans, dumpExplainForHumans, ddExplainForHumans) to my query. But it throws an exception "BadMethodCallException". I debug why it occurred, then i saw you called a protected method `reconnectIfMissingConnection()` of MySqlConnection class inside your `executeQuery()` of DatabaseHelper Class.

```php 
private function executeQuery(Connection $db, string $sql, array $bindings, callable $fn): mixed
{
    $db->reconnectIfMissingConnection();
    $pdo = $db->getPdo();
}
```

If i remove the ` $db->reconnectIfMissingConnection();` method it works fine. Can you fixed it?

### How to reproduce the bug

I explain it like this `Feature::query()->orderBy('id', 'desc')->dumpExplainForHumans();`. It throws the error `Illuminate\Database\MySqlConnection::reconnectIfMissingConnection does not exist`

### Package Version

1.0.0

### PHP Version

8.1

### Laravel Version

9

### Which operating systems does with happen with?

Linux

**Comment by tpetry** [comment]
Sorry for the inconvenience, that was a silly mistake. It is fixed now with version `1.0.1` ;)
